services:
  user:
    image: node:18
    container_name: app_prefeitura_user
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: ${NODE_ENV}
      APPLICATION_PORT: ${APPLICATION_PORT}
      API_KEY: ${API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      MAIL_ADRESS: ${MAIL_ADRESS}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
    ports:
      - 3000
    networks:
      - dokploy-network
networks:
  dokploy-network:
    external: true
